version: '3.8'

services:
  angular-app:
    build:
      context: ./app
    ports:
      - "80:80"

  nest-api:
    build:
      context: ./api
    ports:
      - "3000:3000"
    depends_on:
      - angular-app
