version: '3.8'

services:

  nest-api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    depends_on:
      - angular-app

  angular-app:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
